= Playbook

*My software development playbook – methods and tools for designing, planning,
developing, maintaining and operating software-as-a-service products.*

Many things are needed to make a success of a software project: great leadership,
great people, strong financials, favorable market conditions, and a suitable
process. This documentation is focused on the latter.

Software development is a human-centred process, or a social activity, more
than it is a technical one. Software development is a _system_ in itself, in
the same way that organizations are systems for organizing people and resources
to achieve common goals. A software development methodology is a process or
system that organizes people and resources to deliver IT solutions for target
user groups.


== Contents


* link:./references.adoc[*References*]
  — A list of resources that have influenced the methods and tools documented in
    this engineering playbook.

== Terminology

Throughout this documentation, the following terms, when capitalized, shall
indicate *requirement levels* as defined in
https://datatracker.ietf.org/doc/html/rfc2119[IETF RFC 2119]:
"MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED",  "MAY" and "OPTIONAL".

''''

Copyright © 2020-present Kieran Potts, all rights reserved
