= Technical health checks

While the link:./team-sentiment-surveys.adoc[team sentiment surveys] are focused
on team dynamics and the effectiveness of the software delivery process,
technical health checks are more focused on the quality of the software product
itself.

Technical health checks should be conducted regularly, at least quarterly, and
should cover a variety of metrics that help to gauge the quality of the software
product, and which can be tracked over time to identify trends.

The questions in a technical health check should be objective and answerable
with a simple "Yes", "No" or "I don't know"; alternatively a numerical score of
1 (low) to 5 (high).

[TIP]
======
Google's https://dora.dev/[DevOps Research and Assessment (DORA)] program is
an excellent example of how to capture objective data from developer surveys.
======

Examples of objective survey questions include:

* How long does it take to go from code committed to code successfully running
  in production?

* How often does your organization deploy code to production, or release it to
  users?

