= Context

There are many different kinds of software. Embedded software, system software, utility software, application software, monolithic systems and distributed systems, and so on. Each of these categories of software has its own unique requirements and constraints, and thus each requires a different approach to its development.

There can never be a universal playbook for running all kinds of software projects. That's because software itself is so varied. The optimum approach to developing software will depend very much on the type of software you're making.

For example, the methods and tools used to develop embedded software for a medical device ought to be very different to the methods and tools used to develop a mobile app for a consumer market sector. They're both software systems, but they have very different sets of requirements and technical constraints, and they serve very different commercial sectors and user groups.

This particular playbook is focused on the development of *software-as-a-service (SaaS)* solutions, and with a particular emphasis on *enterprise application software* (EAS). This is a category of software that serves the needs of organizations (public or private sector) rather than individual people, is typically delivered over the web, and which continuously evolves through regular updates.

Basically, this particular software development playbook is optimized for *business web applications* and *web services*.

Of course, this playbook could be used to run other kinds of software projects. It would certainly be a good starting point for all kinds of web-based applications and mobile apps, both business and consumer, as well as digital services that are integrated into other people's applications. But the further away your project is from the SaaS/EAS model, the more you will need to adapt the methods and tools described in this playbook to suit your particular context.
