= Inspiration

Besides the principles of the agile manifesto and the practices of Extreme Programming, this software development playbook has been influenced by numerous other sources, many of which are referenced in footnotes throughout this playbook.

There is nothing, really, in this playbook that is new. The principles, practices, processes, tools, and artifacts presented in this playbook are all well-established in the IT sector. Most of them have been around for decades – some since the very beginning of digital computers.

What is new is the particular synthesis of methods and tools that this playbook presents. It is the _combination_ of methods and tools that is important. They all complement and reinforce each other, and in combination they have been proven to be consistently reliable at delivering successful software projects, including many large scale ones.

The recommended practices of this playbook are based on empirical evidence of what works in practice. Everything in this playbook represents industry best practice, and the processes and practices here are highly regarded by many top professionals in the field of software development.Research papers, case studies, reports and surveys are referenced from footnotes to backup claims made in this playbook.

Yet, not everything here is necessarily _popular_. For example, pair programming has regrettably fallen out of fashion, despite evidence from decades of case studies showing it to be highly effective at delivering high quality software at low cost. Some of the old ways of doing things, like pair programming, should be revisited.

Conversely, there are many practices that _are_ popular in the industry, despite a lack of evidence for their effectiveness. For example, the use of story points in agile project management is widespread, but there is no empirical evidence that story points are any better than other estimation techniques. This playbook does not recommend the use of story points, and offers alternative estimation techniques that provide better accuracy and reliability.

It is worth mentioning that this playbook is guided not only by industry _good_ practice but also by industry _bad_ practice – which is unfortunately widespread. Software projects are notoriously prone to failure: cost overruns, quality issues, and failure to deliver on the promised benefits. Public sector software projects seem to have particularly high failure rates, but that may be because they are funded by taxpayers and are therefore ultimately accountable to the public. We also get to know about large-scale commercial software project failures at publicly-traded companies, because such capital investments get reported to shareholders. For every publicly-visible software project failure there are countless others that are kept confidential.

Failures in software projects are pervasive. Happily, the reasons have been extensively studied, so the root causes – to which there are common patterns – are well understood. The principles that underpin this playbook specifically address these issues.
