= Scope

A software development playbook is a system for organizing people and resources in software development projects. It covers organizational structure, project management, requirements management, change management, and development operations. All of these things are essential if you want to develop high quality software on time and to budget.

But these things are not enough.

Software development is a complex and multifaceted field. Many things are needed to make a success of a software project. Besides a playbook to run software projects, you obviously need motivated individuals with appropriate technical capabilities, and you also need a deep understanding of the real-world problems the software is intended to solve, and of the people and organizations who will use the software.

And, for software to be _commercially_ successful, you need a viable business model, strong financials, favorable market conditions, and much more besides. This playbook is not going to help you with these things. Evaluation of the commercial viability of a software product, and of the business strategy for bringing it to market, are outside the scope of this playbook.

Some software development playbooks also cover *technical standards* and topics related to *software design* and architecture. However, these topics are also out of scope of this particular playbook, which is focused on the human and organizational aspects of software development, rather than the technical aspects. But be in no doubt that technical capability – in both software and hardware (the infrastructure on which the software runs) – is a critical factor in the success of any software project.

Automation of the software development process _is_ in the scope of this playbook, however. This is a topic that is closely related to development operations, and it is a key enabler of the rapid iterative development of software that has proven to be so effective in delivering successful outcomes in software projects.

This playbook has a whole section on *hiring*, because the composition of development teams is another critical factor in successful delivery of software. The focus of this section is on the process of mapping the hard skills and soft skills of individual people to the open roles and responsibilities required to delivery a particular set of software requirements. There is some discussion on best practices for screening and interviewing candidates, for evaluating their skills, and for onboarding new hires. But wider *human resources* management is outside the scope of this playbook. Topics such as training, appraisals, compensation, and retention are not covered here.

Finally, the quality of the work environment, the capabilities of senior management, the effectiveness of governance structures, the culture and values of the organization, and the well-being of the people who work there – all of these things are also hugely important to the success of software projects. But these are not specific to software projects. They apply to all projects, all kinds of collaborative work. A brilliant plan to tackle a software project is not going to resolve deep organizational issues or shield people from the effects of toxic work environments. Well-run projects in such contexts are still very likely to fail.

In summary, the methods and tools set out in this playbook, when used in combination, will significantly increase the chances of successful outcomes in a software development project. And yet this is no silver bullet, no guarantee of success. Many other things, particularly on the technical and commercial sides of the project, are needed too. And a little bit of luck never goes amiss, either.
